version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
      MYSQL_DATABASE: blogdb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_DATABASE: keycloak
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbuserpassword
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: 'false' 
    volumes:
      - ./export:/opt/keycloak/data/import
    ports:
      - '8080:8080'
    networks:
      - blog-network
    depends_on:
      mysql:
        condition: service_healthy
    command: ["start-dev", "--import-realm"]

  quarkus:
    image: quarkus/blog-backend-jvm
    container_name: quarkus
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/blogdb
      QUARKUS_DATASOURCE_USERNAME: dbuser
      QUARKUS_DATASOURCE_PASSWORD: dbuserpassword
      QUARKUS_HTTP_PORT: 8081
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/blog
    ports:
      - '8081:8081'
    networks:
      - blog-network
    depends_on:
      - keycloak
    command: ["sh", "-c", "sleep 120 && java -jar blog-backend-1.0.0.jar"]


networks:
  blog-network:
    driver: bridge

volumes:
  mysql-data: